SELECT ?country ?time ?num WHERE {
  { # begin subquery
     SELECT ?item ?country ?time ?num (COUNT(?time2) as ?next_count)
     WHERE {
      ?item wdt:P31          wd:Q3241045 .
      ?item p:P31/pq:P642    wd:Q84263196 .
      ?item wdt:P17          ?country .
      ?item wdt:P276/wdt:P31 wd:Q6256 .
      # get our main observation data point
        ?item p:P1603 [
          ps:P1603 ?num; 
          pq:P585  ?time ] .
      # find later observations
      OPTIONAL {
        ?item p:P1603 [ pq:P585 ?time2 ] .
      }
      FILTER( ?time2 > ?time )
    }
    GROUP BY ?item ?country ?time ?num
    ORDER BY DESC(?time)
  } #end subquery
  FILTER(?next_count < 3)
} ORDER BY ASC(?item) DESC(?time)
