#endpoint: https://sparql.uniprot.org/sparql/
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX ch:<http://purl.obolibrary.org/obo/>
PREFIX up:<http://purl.uniprot.org/core/>
PREFIX taxon:<http://purl.uniprot.org/taxonomy/>
PREFIX genex: <http://purl.org/genex#>
PREFIX lscr: <http://purl.org/lscr#>

SELECT distinct ?protein ?ensemblGene ?reaction
?anatomicEntityLabel ?anatomicEntity
WHERE {
    SERVICE <https://sparql.rhea-db.org/sparql> {
        ?reaction rdfs:subClassOf rh:Reaction .
        ?reaction rh:equation ?reactionEquation .
        ?reaction rh:side ?reactionSide .
        ?reactionSide rh:contains ?participant .
        ?participant rh:compound ?compound .
        ?compound rh:chebi ch:CHEBI_16113 .
    }

    ?protein up:organism taxon:9606 .
    ?protein up:annotation ?a .
    ?a a up:Catalytic_Activity_Annotation .
    ?a up:catalyticActivity ?ca .
    ?ca up:catalyzedReaction ?reaction .
    ?protein rdfs:seeAlso / up:transcribedFrom ?ensemblGene .

    SERVICE <http://biosoda.expasy.org/rdf4j-server/repositories/bgeelight> {
        ?gene genex:isExpressedIn ?anatomicEntity .
        ?gene lscr:xrefEnsemblGene ?ensemblGene .
        ?anatomicEntity rdfs:label ?anatomicEntityLabel .
    }
}